import { useState } from 'react';
import { Deferred, usePage, router, useForm } from '@inertiajs/react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import {
    Select,
    SelectContent,
    SelectGroup,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import ConfirmModal from '@/components/confirm-modal';
import { X, Plus, Trash2, Edit2, GraduationCap } from 'lucide-react';
import { cn } from '@/lib/utils';
import InputError from '@/components/input-error';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';

// Import route definitions generated by wayfinder
import { store as storeEducation } from '@/routes/candidate/educations';
import { update as updateEducation } from '@/routes/candidate/educations';
import { destroy as destroyEducation } from '@/routes/candidate/educations';

type Education = {
    id: number;
    school_name: string;
    degree: string;
    field_of_study: string | null;
    start_year: number | null;
    end_year: number | null;
    gpa: number | null;
    max_gpa: number | null;
};

type PageProps = {
    candidateProfile: {
        educations: Education[];
    };
};

const DEGREE_OPTIONS = [
    'TK',
    'SD',
    'SMP',
    'SMA',
    'SMK',
    'D1',
    'D2',
    'D3',
    'D4',
    'S1',
    'S2',
    'S3',
];

export default function CandidateEducation() {
    const { candidateProfile } = usePage<PageProps>().props;
    const educations = candidateProfile?.educations ?? [];

    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingId, setEditingId] = useState<number | null>(null);
    const [deleteId, setDeleteId] = useState<number | null>(null);

    const {
        data,
        setData,
        post,
        patch,
        processing,
        errors,
        reset,
        clearErrors,
    } = useForm({
        school_name: '',
        degree: '',
        field_of_study: '',
        start_year: '',
        end_year: '',
        gpa: '',
        max_gpa: '4.00',
    });

    const openAddModal = () => {
        clearErrors();
        reset();
        setEditingId(null);
        setIsModalOpen(true);
    };

    const openEditModal = (education: Education) => {
        clearErrors();
        setData({
            school_name: education.school_name,
            degree: education.degree || '',
            field_of_study: education.field_of_study || '',
            start_year: education.start_year
                ? education.start_year.toString()
                : '',
            end_year: education.end_year ? education.end_year.toString() : '',
            gpa: education.gpa ? education.gpa.toString() : '',
            max_gpa: education.max_gpa ? education.max_gpa.toString() : '4.00',
        });
        setEditingId(education.id);
        setIsModalOpen(true);
    };

    const handleSave = (e: React.FormEvent) => {
        e.preventDefault();

        if (editingId) {
            patch(updateEducation.url({ education: editingId }), {
                preserveScroll: true,
                onSuccess: () => {
                    setIsModalOpen(false);
                    reset();
                },
            });
        } else {
            post(storeEducation.url(), {
                preserveScroll: true,
                onSuccess: () => {
                    setIsModalOpen(false);
                    reset();
                },
            });
        }
    };

    const handleDelete = (id: number) => {
        router.delete(destroyEducation.url({ education: id }), {
            preserveScroll: true,
        });
    };

    return (
        <Card>
            {/* ── Header ── */}
            <CardHeader className="pb-6">
                <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
                    <div className="space-y-1 pr-4">
                        <CardTitle className="flex items-center gap-2">
                            <GraduationCap className="h-5 w-5 text-[#0077b6]" />
                            Pendidikan
                        </CardTitle>
                        <CardDescription>
                            Tambahkan riwayat pendidikan formal Anda dari yang
                            terbaru.
                        </CardDescription>
                    </div>
                    <Button
                        onClick={openAddModal}
                        className="shrink-0 rounded-md bg-[#0077b6] text-white shadow-sm transition-all hover:bg-[#005f92]"
                        size="sm"
                    >
                        <Plus className="mr-1.5 h-4 w-4" />
                        Tambah Pendidikan
                    </Button>
                </div>
            </CardHeader>

            {/* ── Education List ── */}
            <CardContent>
                <div className="relative space-y-4 before:absolute before:inset-y-0 before:left-4 before:w-0.5 before:bg-slate-200">
                    {educations.length === 0 ? (
                        <p className="pl-8 text-sm text-slate-400">
                            Belum ada riwayat pendidikan yang ditambahkan.
                        </p>
                    ) : (
                        educations.map((edu, index) => (
                            <div
                                key={edu.id}
                                className="group relative flex items-start pl-8 transition-all"
                            >
                                {/* Pipeline Dot */}
                                <div className="absolute top-1/2 left-[11px] h-3 w-3 -translate-y-1/2 rounded-full border-2 border-white bg-[#0077b6] ring-2 ring-blue-100" />

                                <div className="flex w-full flex-col justify-between gap-4 py-2 transition-all sm:flex-row sm:items-center">
                                    <div className="flex flex-col">
                                        <h4 className="text-base font-bold text-slate-800">
                                            {edu.school_name}
                                        </h4>
                                        <div className="mt-0.5 flex flex-wrap items-center gap-2 text-sm text-slate-600">
                                            <span className="font-medium text-slate-700">
                                                {edu.degree}
                                            </span>
                                            {edu.field_of_study && (
                                                <>
                                                    <span className="text-slate-300">
                                                        •
                                                    </span>
                                                    <span>
                                                        {edu.field_of_study}
                                                    </span>
                                                </>
                                            )}
                                        </div>
                                        <div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-slate-500">
                                            {(edu.start_year ||
                                                edu.end_year) && (
                                                <span className="inline-flex items-center gap-1 rounded-md bg-blue-50 px-2 py-1 font-semibold text-blue-700">
                                                    {edu.start_year || '???'} -{' '}
                                                    {edu.end_year || 'Sekarang'}
                                                </span>
                                            )}
                                            {edu.gpa && (
                                                <span className="inline-flex items-center gap-1 font-medium text-slate-600">
                                                    <span className="text-slate-400">
                                                        GPA:
                                                    </span>{' '}
                                                    {edu.gpa}{' '}
                                                    <span className="text-slate-300">
                                                        /
                                                    </span>{' '}
                                                    {edu.max_gpa || 4.0}
                                                </span>
                                            )}
                                        </div>
                                    </div>

                                    <div className="flex shrink-0 items-center gap-1 opacity-0 transition-opacity group-hover:opacity-100">
                                        <Button
                                            variant="ghost"
                                            size="icon"
                                            className="h-8 w-8 text-blue-600 hover:bg-blue-50 hover:text-blue-700"
                                            onClick={() => openEditModal(edu)}
                                        >
                                            <Edit2 className="h-4 w-4" />
                                        </Button>
                                        <Button
                                            variant="ghost"
                                            size="icon"
                                            className="h-8 w-8 text-slate-400 hover:bg-red-50 hover:text-red-600"
                                            onClick={() => setDeleteId(edu.id)}
                                        >
                                            <Trash2 className="h-4 w-4" />
                                        </Button>
                                    </div>
                                </div>
                            </div>
                        ))
                    )}
                </div>
            </CardContent>

            {/* ── Modal Add / Edit ── */}
            <Dialog open={isModalOpen} onOpenChange={setIsModalOpen}>
                <DialogContent className="overflow-hidden border-none p-0 shadow-2xl sm:max-w-2xl">
                    <form onSubmit={handleSave}>
                        {/* Modal Header */}
                        <div className="border-b border-slate-100 bg-slate-50 px-6 py-6">
                            <DialogHeader>
                                <DialogTitle className="flex items-center gap-4 text-xl font-bold text-slate-800">
                                    <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-blue-100 text-blue-600 shadow-sm">
                                        <GraduationCap className="h-6 w-6" />
                                    </div>
                                    <div className="flex flex-col gap-1 text-left">
                                        <span>
                                            {editingId
                                                ? 'Edit Riwayat Pendidikan'
                                                : 'Tambah Pendidikan Baru'}
                                        </span>
                                        <DialogDescription className="text-sm font-normal text-slate-500">
                                            Lengkapi detail informasi akademik
                                            Anda di bawah ini.
                                        </DialogDescription>
                                    </div>
                                </DialogTitle>
                            </DialogHeader>
                        </div>

                        {/* Modal Body */}
                        <div className="max-h-[70vh] space-y-8 overflow-y-auto px-6 py-6">
                            {/* Seksi Institusi */}
                            <div className="space-y-4">
                                <h4 className="flex items-center gap-2 border-b border-slate-100 pb-2 text-sm font-semibold text-slate-900">
                                    <span className="flex h-5 w-5 items-center justify-center rounded-full bg-slate-100 text-[10px] text-slate-500">
                                        1
                                    </span>
                                    Informasi Institusi
                                </h4>
                                <div className="grid gap-5">
                                    {/* School Name */}
                                    <div className="grid gap-2">
                                        <Label
                                            htmlFor="school_name"
                                            className="text-slate-600"
                                        >
                                            Nama Institusi{' '}
                                            <span className="text-red-500">
                                                *
                                            </span>
                                        </Label>
                                        <Input
                                            id="school_name"
                                            value={data.school_name}
                                            onChange={(e) =>
                                                setData(
                                                    'school_name',
                                                    e.target.value,
                                                )
                                            }
                                            placeholder="Contoh: Universitas Indonesia"
                                            className="h-11 border-slate-200 focus-visible:ring-blue-500"
                                        />
                                        <InputError
                                            message={errors.school_name}
                                        />
                                    </div>

                                    <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
                                        {/* Degree */}
                                        <div className="grid gap-2">
                                            <Label
                                                htmlFor="degree"
                                                className="text-slate-600"
                                            >
                                                Tingkat Pendidikan
                                            </Label>
                                            <Select
                                                value={data.degree}
                                                onValueChange={(val) =>
                                                    setData('degree', val)
                                                }
                                            >
                                                <SelectTrigger className="h-11 w-full border-slate-200 focus:ring-blue-500">
                                                    <SelectValue placeholder="Pilih Tingkat" />
                                                </SelectTrigger>
                                                <SelectContent>
                                                    <SelectGroup>
                                                        {DEGREE_OPTIONS.map(
                                                            (deg) => (
                                                                <SelectItem
                                                                    key={deg}
                                                                    value={deg}
                                                                >
                                                                    {deg}
                                                                </SelectItem>
                                                            ),
                                                        )}
                                                    </SelectGroup>
                                                </SelectContent>
                                            </Select>
                                            <InputError
                                                message={errors.degree}
                                            />
                                        </div>

                                        {/* Field of Study */}
                                        <div className="grid gap-2">
                                            <Label
                                                htmlFor="field_of_study"
                                                className="text-slate-600"
                                            >
                                                Bidang Studi / Jurusan
                                            </Label>
                                            <Input
                                                id="field_of_study"
                                                value={data.field_of_study}
                                                onChange={(e) =>
                                                    setData(
                                                        'field_of_study',
                                                        e.target.value,
                                                    )
                                                }
                                                placeholder="Contoh: Teknik Informatika"
                                                className="h-11 border-slate-200 focus-visible:ring-blue-500"
                                            />
                                            <InputError
                                                message={errors.field_of_study}
                                            />
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Seksi Waktu & Nilai */}
                            <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
                                {/* Waktu */}
                                <div className="space-y-4">
                                    <h4 className="flex items-center gap-2 border-b border-slate-100 pb-2 text-sm font-semibold text-slate-900">
                                        <span className="flex h-5 w-5 items-center justify-center rounded-full bg-slate-100 text-[10px] text-slate-500">
                                            2
                                        </span>
                                        Periode Studi
                                    </h4>
                                    <div className="grid grid-cols-2 gap-4">
                                        {/* Start Year */}
                                        <div className="grid gap-2">
                                            <Label
                                                htmlFor="start_year"
                                                className="text-slate-600"
                                            >
                                                Tahun Mulai
                                            </Label>
                                            <Input
                                                id="start_year"
                                                type="number"
                                                value={data.start_year}
                                                onChange={(e) =>
                                                    setData(
                                                        'start_year',
                                                        e.target.value,
                                                    )
                                                }
                                                placeholder="YYYY"
                                                className="h-11 border-slate-200 focus-visible:ring-blue-500"
                                            />
                                            <InputError
                                                message={errors.start_year}
                                            />
                                        </div>

                                        {/* End Year */}
                                        <div className="grid gap-2">
                                            <Label
                                                htmlFor="end_year"
                                                className="text-slate-600"
                                            >
                                                Tahun Lulus
                                            </Label>
                                            <Input
                                                id="end_year"
                                                type="number"
                                                value={data.end_year}
                                                onChange={(e) =>
                                                    setData(
                                                        'end_year',
                                                        e.target.value,
                                                    )
                                                }
                                                placeholder="YYYY"
                                                className="h-11 border-slate-200 focus-visible:ring-blue-500"
                                            />
                                            <InputError
                                                message={errors.end_year}
                                            />
                                        </div>
                                    </div>
                                </div>

                                {/* Nilai */}
                                <div className="space-y-4">
                                    <h4 className="flex items-center gap-2 border-b border-slate-100 pb-2 text-sm font-semibold text-slate-900">
                                        <span className="flex h-5 w-5 items-center justify-center rounded-full bg-slate-100 text-[10px] text-slate-500">
                                            3
                                        </span>
                                        Pencapaian Akademik
                                    </h4>
                                    <div className="grid grid-cols-2 gap-4">
                                        {/* GPA */}
                                        <div className="grid gap-2">
                                            <Label
                                                htmlFor="gpa"
                                                className="text-slate-600"
                                            >
                                                Nilai / IPK
                                            </Label>
                                            <Input
                                                id="gpa"
                                                type="number"
                                                step="0.01"
                                                value={data.gpa}
                                                onChange={(e) =>
                                                    setData(
                                                        'gpa',
                                                        e.target.value,
                                                    )
                                                }
                                                placeholder="3.80"
                                                className="h-11 border-slate-200 focus-visible:ring-blue-500"
                                            />
                                            <InputError message={errors.gpa} />
                                        </div>

                                        {/* Max GPA */}
                                        <div className="grid gap-2">
                                            <Label
                                                htmlFor="max_gpa"
                                                className="text-slate-600"
                                            >
                                                Skala Max
                                            </Label>
                                            <Input
                                                id="max_gpa"
                                                type="number"
                                                step="0.01"
                                                value={data.max_gpa}
                                                onChange={(e) =>
                                                    setData(
                                                        'max_gpa',
                                                        e.target.value,
                                                    )
                                                }
                                                placeholder="4.00"
                                                className="h-11 border-slate-200 focus-visible:ring-blue-500"
                                            />
                                            <InputError
                                                message={errors.max_gpa}
                                            />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Modal Footer */}
                        <div className="flex justify-end gap-3 rounded-b-lg border-t border-slate-100 bg-slate-50 px-6 py-4">
                            <Button
                                type="button"
                                variant="outline"
                                onClick={() => setIsModalOpen(false)}
                                className="h-10 px-5 text-slate-600 hover:text-slate-800"
                            >
                                Batal
                            </Button>
                            <Button
                                type="submit"
                                disabled={processing}
                                className="h-10 bg-blue-600 px-6 text-white shadow-sm hover:bg-blue-700"
                            >
                                {processing
                                    ? 'Menyimpan...'
                                    : 'Simpan Pendidikan'}
                            </Button>
                        </div>
                    </form>
                </DialogContent>
            </Dialog>

            {/* ── Modal Delete ── */}
            <ConfirmModal
                isOpen={deleteId !== null}
                onClose={() => setDeleteId(null)}
                onConfirm={() => {
                    if (deleteId !== null) {
                        handleDelete(deleteId);
                        setDeleteId(null);
                    }
                }}
                title="Hapus Pendidikan?"
                description="Apakah Anda yakin ingin menghapus riwayat pendidikan ini dari profil Anda? Tindakan ini tidak dapat dibatalkan."
            />
        </Card>
    );
}
